import { type Action, type Memory, type State, type HandlerCallback } from "@elizaos/core";
import { z } from "zod";

const GenerateProposalSchema = z.object({
  bountyTitle: z.string().optional(),
  bountyRequirements: z.string().optional(),
  userSkills: z.array(z.string()).optional(),
  userName: z.string().optional(),
  userPastWork: z.array(z.string()).optional(),
});

const userProfile = {
  name: "saberdev_123",
  skills: ["React", "Solidity", "Community Manager"],
  pastWork: [
    "Works at FKUSD, HYPERSIGN, NFTFN",
    "$200 earned on Superteam",
    "11 submissions, 1 win",
    "Portfolio: https://saber-dev.vercel.app/",
  ],
  style: {
    tone: "confident and casual",
    approach: "direct, shows relevant experience",
  },
};

function generateProposalTemplate(data: {
  bountyTitle: string;
  bountyRequirements: string;
  userSkills: string[];
  userName: string;
  userPastWork: string[];
}): string {
  const { bountyTitle, userSkills, userName, userPastWork } = data;

  return `**Subject:** ${bountyTitle} — Let's Build Something

Hey!

I just saw the ${bountyTitle} and I'm genuinely excited about this one.

See, I've been working with ${userSkills.slice(0, 2).join(" and ")} for a while now, and this is right up my alley.

**What I'll deliver:**
- [Specific deliverable 1]
- [Specific deliverable 2]
- [Specific deliverable 3]

**Why me:**
${userPastWork.slice(0, 3).map((work) => `- ${work}`).join("\n")}

I can have a working demo ready within [timeframe]. Let me know if you want to discuss further.

Best,
@${userName}

---
*Generated by Oga Wins*`;
}

export const generateProposalAction: Action = {
  name: "GENERATE_PROPOSAL",
  description: "Generates a tailored proposal for Superteam bounties",
  similes: ["WRITE_PROPOSAL", "CREATE_PROPOSAL", "DRAFT_PROPOSAL"],
  validate: async () => true,
  handler: async (
    _runtime,
    _message: Memory,
    _state: State | undefined,
    options: {
      bountyTitle?: string;
      bountyRequirements?: string;
      userSkills?: string[];
      userName?: string;
      userPastWork?: string[];
    },
    _callback?: HandlerCallback
  ) => {
    const params = GenerateProposalSchema.parse(options);
    
    const skills = options.userSkills || userProfile.skills;
    const pastWork = options.userPastWork || userProfile.pastWork;
    const userName = options.userName || userProfile.name;
    const title = options.bountyTitle || "Project";

    const proposal = generateProposalTemplate({
      bountyTitle: title,
      bountyRequirements: params.bountyRequirements || "",
      userSkills: skills,
      userName: userName,
      userPastWork: pastWork,
    });

    return {
      success: true,
      proposal,
      tips: [
        "Fill in the [Specific deliverable] sections with concrete outputs",
        "Adjust the timeframe based on your availability",
        "Review and personalize before submitting",
      ],
    };
  },
  examples: [
    [
      { name: "user", content: { text: "Write a proposal for the Nosana bounty" } },
      { name: "Oga Wins", content: { text: "Abeg, I go generate proposal for you now!" } },
    ],
  ],
};

export const getUserProfileAction: Action = {
  name: "GET_USER_PROFILE",
  description: "Returns the user's profile information",
  similes: ["MY_PROFILE", "MY_INFO", "SHOW_PROFILE"],
  validate: async () => true,
  handler: async (
    _runtime,
    _message: Memory,
    _state: State | undefined
  ) => {
    return {
      success: true,
      profile: userProfile,
    };
  },
  examples: [
    [
      { name: "user", content: { text: "What's my profile?" } },
      { name: "Oga Wins", content: { text: "Your profile shows you get React and Solidity skills" } },
    ],
  ],
};

export default {
  name: "proposal-generator",
  description: "Generates tailored proposals for bounties",
  actions: [generateProposalAction, getUserProfileAction],
};
