import { type Action, type Memory, type State, type HandlerCallback } from "@elizaos/core";
import { z } from "zod";

const GenerateProposalSchema = z.object({
  bountyTitle: z.string().describe("Title of the bounty/project"),
  bountyRequirements: z.string().describe("Requirements or description of the bounty"),
  userSkills: z.array(z.string()).optional().describe("User's skills (defaults to React, Solidity)"),
  userName: z.string().optional().describe("User's name (defaults to saberdev_123)"),
  userPastWork: z.string().optional().describe("User's past work or experience"),
});

const userProfile = {
  name: "saberdev_123",
  skills: ["React", "Solidity", "Community Manager"],
  pastWork: [
    "Works at FKUSD, HYPERSIGN, NFTFN",
    "$200 earned on Superteam",
    "11 submissions, 1 win",
    "Portfolio: https://saber-dev.vercel.app/",
    "GitHub: https://github.com/Saber1Y",
    "Twitter: @Sabercodes123",
  ],
  style: {
    tone: "confident and casual",
    approach: "direct, shows relevant experience, proposes concrete deliverable",
  },
};

function generateProposalTemplate(data: {
  bountyTitle: string;
  bountyRequirements: string;
  userSkills: string[];
  userName: string;
  userPastWork: string[];
}): string {
  const { bountyTitle, bountyRequirements, userSkills, userName, userPastWork } = data;

  return `**Subject:** ${bountyTitle} — Let's Build Something 🔥

Hey!

I just saw the ${bountyTitle} and I'm genuinely excited about this one.

See, I've been working with ${userSkills.slice(0, 2).join(" and ")} for a while now, and this is right up my alley.

**What I'll deliver:**
- [Specific deliverable 1]
- [Specific deliverable 2]
- [Specific deliverable 3]

**Why me:**
${userPastWork.slice(0, 3).map((work, i) => `- ${work}`).join("\n")}

I can have a working demo ready within [timeframe]. Let me know if you want to discuss further.

Best,
@${userName}

---
*Generated by BountyStack Agent*`;
}

export const generateProposalAction: Action = {
  name: "GENERATE_PROPOSAL",
  description: "Generates a tailored proposal for Superteam bounties based on user's skills and past work. Creates professional proposals in the user's voice.",
  similes: ["WRITE_PROPOSAL", "CREATE_PROPOSAL", "DRAFT_PROPOSAL", "MAKE_PROPOSAL"],
  validate: async (_runtime, _message) => {
    return true;
  },
  handler: async (
    _runtime,
    _message: Memory,
    _state: State,
    options: {
      bountyTitle?: string;
      bountyRequirements?: string;
      userSkills?: string[];
      userName?: string;
      userPastWork?: string[];
    },
    _callback?: HandlerCallback
  ) => {
    const params = GenerateProposalSchema.parse({
      bountyTitle: options.bountyTitle || "Project",
      bountyRequirements: options.bountyRequirements || "",
      userSkills: options.userSkills || userProfile.skills,
      userName: options.userName || userProfile.name,
      userPastWork: options.userPastWork || userProfile.pastWork,
    });

    const proposal = generateProposalTemplate({
      bountyTitle: params.bountyTitle,
      bountyRequirements: params.bountyRequirements,
      userSkills: params.userSkills,
      userName: params.userName,
      userPastWork: params.userPastWork,
    });

    return {
      success: true,
      proposal,
      tips: [
        "Fill in the [Specific deliverable] sections with concrete outputs",
        "Adjust the timeframe based on your availability",
        "Review and personalize before submitting",
        "Keep it to 2-3 paragraphs max",
      ],
    };
  },
  examples: [
    [
      {
        user: "{{user1}}",
        content: { text: "Write a proposal for the Nosana bounty" },
      },
      {
        user: "BountyStack",
        content: {
          text: "Abeg, I go generate proposal for you now. Based on your skills and past work, I go make am tight!",
        },
      },
    ],
    [
      {
        user: "{{user1}}",
        content: { text: "Create a proposal for the React dashboard bounty" },
      },
      {
        user: "BountyStack",
        content: {
          text: "I dey on it! Your proposal go be fire! 🔥",
        },
      },
    ],
  ],
};

export const getUserProfileAction: Action = {
  name: "GET_USER_PROFILE",
  description: "Returns the user's Superteam profile information including skills, past work, and proposal style.",
  similes: ["MY_PROFILE", "MY_INFO", "SHOW_PROFILE", "MY_DETAILS"],
  validate: async (_runtime, _message) => {
    return true;
  },
  handler: async (_runtime, _message: Memory, _state: State) => {
    return {
      success: true,
      profile: userProfile,
    };
  },
  examples: [
    [
      {
        user: "{{user1}}",
        content: { text: "What's my profile?" },
      },
      {
        user: "BountyStack",
        content: {
          text: "Your profile shows you get React, Solidity, and community management skills. You don work with FKUSD, HYPERSIGN, and NFTFN before.",
        },
      },
    ],
  ],
};

export default {
  name: "proposal-generator",
  description: "Generates tailored proposals for Superteam bounties based on user's skills and past work",
  actions: [generateProposalAction, getUserProfileAction],
};
